@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam arrowFontSize 11
skinparam classBackgroundColor MODEL_COLOR
skinparam responseMessageBelowArrow true

Class Contact
Class Event
Class Name
Class Email
Class Phone
Class Address
Class EventStatus
Class Date
Class Tag

Contact *--> "1" Name
Contact *--> "1" Email
Contact *--> "1" Phone
Contact *--> "1" Address
Contact *--> "~*" Tag

Event *--> "1" Name
Event *--> "1" EventStatus
Event *--> "1" Date
Event *--> "1" Address
Event *--> "~*" Tag

Name -right[hidden]- Tag
Tag -right[hidden]- Address
Contact -right[hidden]- Event
@enduml
