@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AppData Storage" #F4F6F6{
Class "<<interface>>\nAppDataStorage" as AppDataStorage
Class JsonAppDataStorage
Class JsonSerializableAppData
Class JsonAdaptedEvent
Class JsonAdaptedContact
Class JsonAdaptedTag
Class JsonAdaptedParticipant
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AppDataStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AppDataStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAppDataStorage .right.|> AppDataStorage
JsonAppDataStorage ..> JsonSerializableAppData
JsonSerializableAppData --> "*" JsonAdaptedContact
JsonAdaptedContact --> "*" JsonAdaptedTag
JsonAdaptedEvent --> "*" JsonAdaptedParticipant
JsonAdaptedEvent --> "*" JsonAdaptedTag
JsonSerializableAppData --> "*" JsonAdaptedEvent

@enduml
