@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class ContactListPanel
Class ContactCard
Class EventListPanel
Class EventCard
Class ListHeading
Class PrefixedList
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow

MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" ContactListPanel
MainWindow *-down-> "1" EventListPanel
MainWindow *-down-> "1" StatusBarFooter

ContactListPanel -down-> "*" ContactCard
EventListPanel -down-> "*" EventCard

MainWindow -----|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
ContactListPanel --|> UiPart
ContactCard --|> UiPart
EventListPanel --|> UiPart
EventCard --|> UiPart
StatusBarFooter --|> UiPart

ContactCard ...> Model
EventCard ...> Model

UiManager -right-> Logic
MainWindow -right-> Logic

ContactListPanel ..> PrefixedList
EventListPanel ..> PrefixedList

ContactListPanel ..> ListHeading
EventListPanel ..> ListHeading

ContactListPanel -[hidden]left- EventListPanel
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
